package com.TTNProject.EcommerceWebsite.EnumOrderStatus;

public enum Status {
    OREDER_PLACED,CANCELLED,ORDER_REJEJCTED,ORDER_CONFIRMED,ORDER_SHIPPED,DELIVERED,
    RETURN_REQUESTED,RETURN_APPROVED,PICK_UP_INITIATED,PICK_UP_COMPLETED,REFUND_INITIATED,REFUND_COMPLETED
}
